name: flutter_lodz_ble
description: "Fun with BLE"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  bloc: 8.1.4
  bluetooth_low_energy: 6.0.2
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_blue_plus: 1.34.5
  permission_handler: 11.3.1
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
